# Generated by Django 5.2.4 on 2025-07-03 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resourcelink',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='resources/'),
        ),
        migrations.AlterField(
            model_name='resourcelink',
            name='url',
            field=models.URLField(blank=True),
        ),
    ]
