# Generated by Django 5.2.4 on 2025-07-04 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_resourcelink_pdf_alter_resourcelink_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itineraryevent',
            name='day',
            field=models.IntegerField(choices=[(1, 'Day 1'), (2, 'Day 2')]),
        ),
    ]
