# Generated by Django for ItineraryEvent time field migration
from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_alter_itineraryevent_day"),
    ]

    operations = [
        migrations.AddField(
            model_name="itineraryevent",
            name="start_time",
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name="itineraryevent",
            name="end_time",
            field=models.TimeField(null=True),
        ),
        migrations.RunSQL(
            sql="UPDATE main_itineraryevent SET start_time = '09:00', end_time = '10:00' WHERE start_time IS NULL;",
            reverse_sql="UPDATE main_itineraryevent SET start_time = NULL, end_time = NULL;",
        ),
        migrations.RemoveField(
            model_name="itineraryevent",
            name="time",
        ),
        migrations.AlterField(
            model_name="itineraryevent",
            name="start_time",
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name="itineraryevent",
            name="end_time",
            field=models.TimeField(),
        ),
    ]
