# Generated by Django 5.2.4 on 2025-07-04 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_itineraryevent_timefields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itineraryevent',
            options={'ordering': ['day', 'start_time']},
        ),
    ]
