# Generated by Django 5.2.4 on 2025-07-07 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_itineraryevent_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='committeemember',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='committeemember',
            name='photo',
        ),
    ]
